Cars/Cars/Models/Ad.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cars.Models
{
    public class Ad
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Input Value")]
        [Display(Name="Year")]
        [Range(0,3000, ErrorMessage = "Year mut be in range (0-3000)")]
        public int Year { get; set; }

        [Required(ErrorMessage = "Input Value")]
        [Display(Name = "Engine Volume")]
        [Range(0, 30, ErrorMessage = "Volume mut be in range (0-30)")]
        public double EngineVolume { get; set; }

        [Required(ErrorMessage = "Input Value")]
        [Range(typeof(decimal), "0.00", "1000000000.99")]
        public decimal Cost { get; set; }

        [Required(ErrorMessage = "Input Value")]
        public int Mileage { get; set; }

        [Required(ErrorMessage = "Input Value")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        public string VendorText { get; set; }

        [Required(ErrorMessage = "Input Value")]
        public int ModelId { get; set; }
        public Model Model { get; set; }

        [Required(ErrorMessage = "Input Value")]
        public int GearBoxId { get; set; }
        public GearBox GearBox { get; set; }

        [Required(ErrorMessage = "Input Value")]
        public int ColorId { get; set; }
        public Color Color { get; set; }

        [Required(ErrorMessage = "Input Value")]
        public int FuelTypeId { get; set; }
        public FuelType FuelType { get; set; }

        [Required(ErrorMessage = "Input Value")]
        public int VendorId { get; set; }
        public Vendor Vendor { get; set; }
    }
}

Cars/Cars/ViewModels/AdViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cars.Models;

namespace Cars.ViewModels
{
    public class AdViewModel
    {
        public Ad Ad { get; set; }
        public SelectList BrandSelectList { get; set; }
        public SelectList GearBoxSelectList { get; set; }
        public SelectList ColorSelectList { get; set; }
        public SelectList FuelTypeSelectList { get; set; }
        public SelectList VendorSelectList { get; set; }

        public SelectList ModelSelectList { get; set; }



    }
}

Cars/Cars/Controllers/AdController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Cars.Models;
using Cars.ViewModels;

namespace Cars.Controllers
{
    public class AdController : Controller
    {
        CarContext db = new CarContext();
        [HttpGet]
        public async Task<ActionResult> Index(CombineViewModel cm)
        {
            var gBoxes = await db.GearBoxes.ToListAsync();
            var fTypes = await db.FuelTypes.ToListAsync();

            cm = cm ?? new CombineViewModel();

            cm.AdViewModel = new AdViewModel();
            cm.AdViewModel.ColorSelectList = new SelectList(await db.Colors.ToListAsync(),
                nameof(Color.Id), nameof(Color.Name));
            cm.AdViewModel.FuelTypeSelectList = new SelectList(fTypes,
                nameof(FuelType.Id), nameof(FuelType.TypeName));
            cm.AdViewModel.GearBoxSelectList = new SelectList(gBoxes,
                nameof(GearBox.Id), nameof(GearBox.BoxType));

            cm.AdViewModel.BrandSelectList = new SelectList(await db.Brands.ToListAsync(),
                nameof(Model.Id), nameof(Model.Name));

            cm.AdViewModel.VendorSelectList = new SelectList(await db.Vendors.ToListAsync(),
                nameof(Vendor.Id), nameof(Vendor.Name));

            if (cm.FilterViewModel == null)
            {
                cm.FilterViewModel = new FilterViewModel();

                cm.FilterViewModel.GearBoxCkBoxItems = gBoxes.Select(c => new CheckBoxItem()
                {
                    CheckBoxId = c.Id,
                    ItemName = c.BoxType,
                    IsChecked = false
                }).ToList();

                cm.FilterViewModel.FuelTypeCkBoxItems = fTypes.Select(c => new CheckBoxItem()
                {
                    CheckBoxId = c.Id,
                    ItemName = c.TypeName,
                    IsChecked = false
                }).ToList();

                cm.Ad = await db.Ads
                    .Include(c => c.Model.Brand)
                    .Include(c => c.Color)
                    .Include(c => c.FuelType)
                    .Include(c => c.GearBox)
                    .Include(c => c.Vendor)
                    .ToListAsync();
                return View(cm);
            }
           

            var data = db.Ads
                .Include(c => c.Model.Brand)
                .Include(c => c.Color)
                .Include(c => c.FuelType)
                .Include(c => c.GearBox)
                .Include(c => c.Vendor);

            if (cm.FilterViewModel.ColorId != null)
            {
                data = data.Where(c => c.ColorId == cm.FilterViewModel.ColorId);
            }

            if (cm.FilterViewModel.BrandId != null)
            {
                data = data.Where(c => c.Model.BrandId == cm.FilterViewModel.BrandId);
            }

            if (cm.FilterViewModel.ModelId != null)
            {
                data = data.Where(c => c.ModelId == cm.FilterViewModel.ModelId);
            }

            if (cm.FilterViewModel.PriceFrom > 0)
            {
                data = data.Where(c => c.Cost > cm.FilterViewModel.PriceFrom);
            }

            if (cm.FilterViewModel.PriceTo > 0)
            {
                data = data.Where(c => c.Cost < cm.FilterViewModel.PriceTo);
            }

            if (cm.FilterViewModel.YearFrom > 0)
            {
                data = data.Where(c => c.Cost >= cm.FilterViewModel.YearFrom);
            }

            if (cm.FilterViewModel.YearTo > 0)
            {
                data = data.Where(c => c.Cost <= cm.FilterViewModel.YearTo);
            }

            if (cm.FilterViewModel.GearBoxCkBoxItems.Count(c => c.IsChecked) > 0)
            {
                List<int> checkedItems = cm.FilterViewModel.GearBoxCkBoxItems.Where(c => c.IsChecked).Select(c => c.CheckBoxId).ToList();
                //where gearboxId IN checkedItems
                data = data.Where(c => checkedItems.Contains(c.GearBoxId));

                cm.FilterViewModel.GearBoxCkBoxItems = gBoxes.Select(c => new CheckBoxItem()
                {
                    CheckBoxId = c.Id,
                    ItemName = c.BoxType,
                    IsChecked = checkedItems.Contains(c.Id)
                }).ToList();

            }
            else
            {
                cm.FilterViewModel.GearBoxCkBoxItems = gBoxes.Select(c => new CheckBoxItem()
                {
                    CheckBoxId = c.Id,
                    ItemName = c.BoxType,
                    IsChecked = false
                }).ToList();
            }

            if (cm.FilterViewModel.FuelTypeCkBoxItems.Count(c => c.IsChecked) > 0)
            {
                List<int> checkedItems = cm.FilterViewModel.FuelTypeCkBoxItems.Where(c => c.IsChecked)
                    .Select(c => c.CheckBoxId).ToList();
                data = data.Where(c => checkedItems.Contains(c.FuelTypeId));

                cm.FilterViewModel.FuelTypeCkBoxItems = fTypes.Select(c => new CheckBoxItem()
                {
                    CheckBoxId = c.Id,
                    ItemName = c.TypeName,
                    IsChecked = checkedItems.Contains(c.Id)
                }).ToList();
            }
            else
            {
                cm.FilterViewModel.FuelTypeCkBoxItems = fTypes.Select(c => new CheckBoxItem()
                {
                    CheckBoxId = c.Id,
                    ItemName = c.TypeName,
                    IsChecked = false
                }).ToList();
            }

            cm.Ad = await data.ToListAsync(); 

            return View(cm);
            
            

            
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            AdViewModel ad = new AdViewModel();
            ad.ColorSelectList = new SelectList(await db.Colors.ToListAsync(),
                nameof(Color.Id),nameof(Color.Name));
            ad.FuelTypeSelectList = new SelectList(await db.FuelTypes.ToListAsync(),
                nameof(FuelType.Id), nameof(FuelType.TypeName));
            ad.GearBoxSelectList = new SelectList(await db.GearBoxes.ToListAsync(),
                nameof(GearBox.Id), nameof(GearBox.BoxType));

            ad.BrandSelectList = new SelectList(await db.Brands.ToListAsync(),
                nameof(Model.Id), nameof(Model.Name));

            ad.VendorSelectList = new SelectList(await db.Vendors.ToListAsync(),
                nameof(Vendor.Id), nameof(Vendor.Name));
            return View(ad);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AdViewModel adVm)
        {
            if (!ModelState.IsValid) return HttpNotFound();
            db.Ads.Add(adVm.Ad);
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            AdViewModel ad = new AdViewModel();

            ad.Ad = await db.Ads.FirstOrDefaultAsync(c => c.Id == id);
            if (ad.Ad == null) return HttpNotFound();

            ad.ColorSelectList = new SelectList(await db.Colors.ToListAsync(),
                nameof(Color.Id), nameof(Color.Name));
            ad.FuelTypeSelectList = new SelectList(await db.FuelTypes.ToListAsync(),
                nameof(FuelType.Id), nameof(FuelType.TypeName));
            ad.GearBoxSelectList = new SelectList(await db.GearBoxes.ToListAsync(),
                nameof(GearBox.Id), nameof(GearBox.BoxType));

            ad.BrandSelectList = new SelectList(await db.Brands.ToListAsync(),
                nameof(Model.Id), nameof(Model.Name));

            ad.VendorSelectList = new SelectList(await db.Vendors.ToListAsync(),
                nameof(Vendor.Id), nameof(Vendor.Name));

            ad.ModelSelectList = new SelectList(await db.Models.ToListAsync(),
                nameof(Model.Id), nameof(Model.Name));

            return View(ad);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(AdViewModel adwm)
        {
            if (!ModelState.IsValid) return HttpNotFound();

            db.Entry(adwm.Ad).State = EntityState.Modified;
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> GetModels(int brandId)
        {
            ModelViewModel mv = new ModelViewModel();
            mv.ModelSelectList = new SelectList(await db.Models
                .Where(b => b.BrandId == brandId).ToListAsync(),
                nameof(Model.Id), nameof(Model.Name));
            return PartialView(mv);
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Cars/Cars/Views/Ad/Create.cshtml
@model Cars.ViewModels.AdViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Ad</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Ad.Year, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ad.Year, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ad.Year, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ad.EngineVolume, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ad.EngineVolume, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ad.EngineVolume, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ad.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ad.Cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ad.Cost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ad.Mileage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ad.Mileage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ad.Mileage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ad.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ad.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ad.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ad.VendorText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ad.VendorText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ad.VendorText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="brId" class="control-label col-md-2">Brand</label>
        <div class="col-md-10">
            @Html.DropDownList("brId", Model.BrandSelectList, "Choose Brand", htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group" id="modelsDiv">
        
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ad.GearBoxId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Ad.GearBoxId, Model.GearBoxSelectList, "Choose", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Ad.GearBoxId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ad.ColorId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Ad.ColorId, Model.ColorSelectList, "Choose", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Ad.ColorId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ad.FuelTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Ad.FuelTypeId, Model.FuelTypeSelectList, "Choose", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Ad.FuelTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ad.VendorId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Ad.VendorId, Model.VendorSelectList, "Choose", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Ad.VendorId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ajax")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#brId').change(function () {
                var id = $('#brId')[0].value;
                $('#modelsDiv').load('@Url.Action("GetModels", "Ad")?brandId=' + id);
            });
        });
    </script>
}

Cars/Cars/Views/Ad/GetModels.cshtml
@model Cars.ViewModels.ModelViewModel


    @Html.LabelFor(model => model.Ad.ModelId, 
        htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownListFor(m => m.Ad.ModelId, 
            Model.ModelSelectList, "Choose Model", htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Ad.ModelId, 
            "", new { @class = "text-danger" })
    </div>

Cars/Cars/Views/Ad/Index.cshtml
@model Cars.ViewModels.CombineViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


<div>
    <h3>Filter List:</h3>
    @using (Html.BeginForm("Index", "Ad", FormMethod.Get))
    {

        <div class="form-group">
            @Html.LabelFor(model => model.FilterViewModel.ColorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.FilterViewModel.ColorId, Model.AdViewModel.ColorSelectList, "Choose", htmlAttributes: new { @class = "form-control" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilterViewModel.BrandId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.FilterViewModel.BrandId, Model.AdViewModel.BrandSelectList, "Choose brand", htmlAttributes: new { @class = "form-control" })
               
            </div>
        </div>

        <div class="form-group" id="modelsDiv">

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilterViewModel.PriceFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.FilterViewModel.PriceFrom, new { htmlattributes = new { @class = "form-control" } })
               
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilterViewModel.PriceTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.FilterViewModel.PriceTo, new { htmlattributes = new { @class = "form-control" } })
              
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilterViewModel.YearFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.FilterViewModel.YearFrom, new { htmlattributes = new { @class = "form-control" } })
               
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilterViewModel.YearTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.FilterViewModel.YearTo, new { htmlattributes = new { @class = "form-control" } })
               
            </div>
        </div>
        <br/>
        
        <div class="form-group">
            @Html.LabelFor(m => m.FilterViewModel.GearBoxCkBoxItems)
                <table class="table">
                    @for (int i = 0; i < Model.FilterViewModel.GearBoxCkBoxItems.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.HiddenFor(m => m.FilterViewModel.GearBoxCkBoxItems[i].CheckBoxId)
                                @Html.DisplayFor(m => m.FilterViewModel.GearBoxCkBoxItems[i].ItemName)
                            </td>
                            <td>
                                @Html.CheckBoxFor(m => m.FilterViewModel.GearBoxCkBoxItems[i].IsChecked)
                            </td>
                        </tr>

                    }
                </table>
            
        </div>
        <br/>
        <div class="form-group">
            @Html.LabelFor(m => m.FilterViewModel.FuelTypeCkBoxItems)
                <table class="table">
                    @for (int i = 0; i < Model.FilterViewModel.FuelTypeCkBoxItems.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.HiddenFor(m => m.FilterViewModel.FuelTypeCkBoxItems[i].CheckBoxId)
                                @Html.DisplayFor(m => m.FilterViewModel.FuelTypeCkBoxItems[i].ItemName)
                            </td>
                            <td>
                                @Html.CheckBoxFor(m => m.FilterViewModel.FuelTypeCkBoxItems[i].IsChecked)
                            </td>
                        </tr>

                    }
                </table>
            
        </div>
        <br/>
        <input type="submit" class="btn btn-primary" />
    }
</div>
<hr/>
<h3>List Of Items</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].Color.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].FuelType.TypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].GearBox.BoxType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].Model.Brand.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].Model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].Vendor.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].Year)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].EngineVolume)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].Cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].Mileage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ad[0].VendorText)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Ad)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Color.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuelType.TypeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GearBox.BoxType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model.Brand.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vendor.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EngineVolume)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mileage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VendorText)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ajax")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#FilterViewModel_BrandId').change(function () {
                var id = $('#FilterViewModel_BrandId')[0].value;
                $('#modelsDiv').load('@Url.Action("GetModels", "Ad")?brandId=' + id);
            });
        });
    </script>
}